<a href="https://colab.research.google.com/github/khushiravtode/College-ERP/blob/main/IDS_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3,5])
print(a)

[1 2 3 5]


In [ ]:
a1=[1,2,3,4,5]
print(a1)


[1, 2, 3, 4, 5]


In [ ]:
print(a.ndim)

1


In [ ]:
a=np.array(34)
print(a.ndim)


0


In [ ]:
a2=np.array([[1,2,3],[4,5,6]])
print(a2)
print(a2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a3)
print(a3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [ ]:
print(a2.shape)p=[0.4,0.2,0.1,0.3]

(2, 3)


In [ ]:
print(a3.shape)

(1, 3, 3)


In [ ]:
arr5=np.arange(10)
print(arr5)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr=np.arange(2,10)
print(arr)

[2 3 4 5 6 7 8 9]


In [ ]:
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [ ]:
arr=np.arange(10,0,-1)
print(arr)

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
arr=np.zeros(5,dtype=int)
print(arr)

[0 0 0 0 0]


In [ ]:
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=np.zeros((2,3),dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]]


In [ ]:
arr=np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [ ]:
arr=np.ones(5,dtype=int)
print(arr)

[1 1 1 1 1]


In [ ]:
arr=np.random.rand(5)
print(arr)

[0.38653998 0.24971457 0.22022458 0.32420267 0.45083377]


In [ ]:
arr=np.random.rand(4,5,3)
print(arr)


[[[0.63735186 0.59286207 0.82285397]
  [0.16535642 0.24889639 0.06483638]
  [0.6203411  0.15599486 0.86210551]
  [0.58927489 0.79614906 0.72563816]
  [0.75785422 0.57932261 0.83809174]]

 [[0.70816698 0.77321247 0.41147602]
  [0.72307238 0.70752721 0.63412657]
  [0.4110998  0.78729257 0.0399003 ]
  [0.313729   0.82042826 0.60052224]
  [0.24187393 0.49401058 0.76957226]]

 [[0.46664124 0.98090804 0.21588019]
  [0.94614059 0.85647908 0.69795275]
  [0.45318626 0.25134835 0.05710743]
  [0.98997176 0.18493566 0.67365206]
  [0.95122619 0.31379812 0.12567541]]

 [[0.63013039 0.03018951 0.94517337]
  [0.92582034 0.46185206 0.15200881]
  [0.29365826 0.91322317 0.3143619 ]
  [0.1272873  0.69640356 0.55604351]
  [0.99161185 0.99542798 0.84766506]]]


In [ ]:
arr=np.random.randint(1,10)
print(arr)

3


In [ ]:
arr=np.random.randint(1,10,10)
print(arr)

[1 2 6 4 9 9 7 5 1 5]


In [ ]:
arr=np.empty(7)
print(arr)

[7.84137125e-316 0.00000000e+000 0.00000000e+000 1.63041663e-322
 7.63376640e-316 6.62118304e-310 2.37151510e-321]


In [ ]:
f=np.full((2,3),8)
print(f)

[[8 8 8]
 [8 8 8]]


In [ ]:
g=np.full((2,2),np.inf)
print(g)

[[inf inf]
 [inf inf]]


In [ ]:
ls=np.linspace(0,1,5)
print(ls)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
ls=np.linspace(0,10)
print(ls)
print(ls.size)



[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
50


In [ ]:
ls=np.linspace(0,20)
print(ls)
print(ls.size)

[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]
50


In [ ]:
arr=np.arange(20,0,-1)
print(arr)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [ ]:
ls=np.linspace(1,5,10)
print(ls)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
arr1=np.random.randint(200,300,10)
print(arr1)

[224 251 289 220 244 279 275 287 223 294]


In [ ]:
arr1=np.random.uniform(200,300,10)
print(arr1)

[295.6718606  210.20553592 239.43851399 287.925002   245.56945887
 216.64518158 265.75419799 235.80170733 288.77352977 266.51848751]


In [ ]:
v=np.logspace(1,5,10)
print(v)

[1.00000000e+01 2.78255940e+01 7.74263683e+01 2.15443469e+02
 5.99484250e+02 1.66810054e+03 4.64158883e+03 1.29154967e+04
 3.59381366e+04 1.00000000e+05]


In [ ]:
v1=np.array([[2,2,1],[3,3,1]])
print(v1)
print(v1.T)

[[2 2 1]
 [3 3 1]]
[[2 3]
 [2 3]
 [1 1]]


In [ ]:
i=np.array([[1,2,3,4],[5,6,7,1],[2,4,5,6]])
print(i)

[[1 2 3 4]
 [5 6 7 1]
 [2 4 5 6]]


In [ ]:
arr = np.random.randint(1, 12, 12).reshape(4,3)
print(arr)

[[ 6  6  9]
 [ 5  6  8]
 [ 9 11  3]
 [ 6  2  5]]
